name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_wasmer:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Setup wasi-sdk
        run: |
          curl -L https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz | tar -xz
          mv wasi-sdk-12.0 /opt/wasi-sdk
          echo "WASI_SDK_PATH=/opt/wasi-sdk" >> $GITHUB_ENV

      - name: Setup wasmer
        run: |
          curl https://get.wasmer.io -sSfL | bash
          echo "$HOME/.wasmer/bin" >> $GITHUB_PATH

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build tests
        run: bash build.sh

      - name: Run tests
        run: bash test.sh wasmer

  test_wasmtime:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Setup wasi-sdk
        run: |
          curl -L https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz | tar -xz
          mv wasi-sdk-12.0 /opt/wasi-sdk
          echo "WASI_SDK_PATH=/opt/wasi-sdk" >> $GITHUB_ENV

      - name: Setup wasmtime
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build tests
        run: bash build.sh

      - name: Run tests
        run: bash test.sh wasmtime

