name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_wasmer:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Setup rust
        uses: hecrj/setup-rust-action@v1
        with:
          targets: "wasm32-wasi"

      - name: Setup wasmer
        run: |
          curl https://get.wasmer.io -sSfL | bash
          echo "$HOME/.wasmer/bin" >> $GITHUB_PATH

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build tests
        run: bash build.sh

      - name: Run tests
        run: bash test.sh wasmer

  test_wasmtime:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Setup rust
        uses: hecrj/setup-rust-action@v1
        with:
          targets: "wasm32-wasi"

      - name: Setup wasmtime
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build tests
        run: bash build.sh

      - name: Run tests
        run: bash test.sh wasmtime

