name: sync
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  core:
    name: sync (core)
    concurrency: commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: caspervonb/wasi-core-test
          path: core

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Setup assemblyscript
        run: |
          npm install -g assemblyscript

      - name: Build tests
        working-directory: core
        run: bash build.sh

      - name: Commit changes
        run: |
          git config user.name "Casper Beyer"
          git config user.email "caspervonb@pm.me"
          git add -A core
          git add -f core/*.wasm
          git commit -m "Update core to $(git -C core rev-parse --short HEAD)"
          git push

  libc:
    name: sync (libc)
    concurrency: commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: caspervonb/wasi-libc-test
          path: libc

      - name: Setup wasi-sdk
        run: |
          curl -L https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz | tar -xz
          mv wasi-sdk-12.0 /opt/wasi-sdk
          echo "CC=/opt/wasi-sdk/bin/clang" >> $GITHUB_ENV
          echo "WASI_SDK_PATH=/opt/wasi-sdk" >> $GITHUB_ENV

      - name: Build tests
        working-directory: libc
        run: bash build.sh

      - name: Commit changes
        run: |
          git config user.name "Casper Beyer"
          git config user.email "caspervonb@pm.me"
          git add -A libc
          git add -f libc/*.wasm
          git commit -m "Update libc to $(git -C libc rev-parse --short HEAD)"
          git push

  libstd:
    name: sync (libstd)
    concurrency: commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: caspervonb/wasi-libstd-test
          path: libstd

      - name: Setup wasm32-wasi
        run: |
          rustup target add wasm32-wasi

      - name: Build tests
        working-directory: libstd
        run: bash build.sh

      - name: Commit changes
        run: |
          git config user.name "Casper Beyer"
          git config user.email "caspervonb@pm.me"
          git add -A libstd
          git add -f libstd/*.wasm
          git commit -m "Update libstd to $(git -C libc rev-parse --short HEAD)"
          git push